### PR TITLE
custom mempool server fixes [has DB changes]

### LINKED ISSUE #1741: mempool custom server validation checker bug
The mempool custom server validation checker is unable to verify a local private server certificate, thus not allowing me to add my custom mempool server. Screenshots attached. 

Image

Image

### PR DESCRIPTION
**Pull request by basantagoswami**
Fixes #1741 and a few other things

1. Added a toggle called enable SSL which is auto-detected from the protocol prefix (http:// vs https://)
2. User can override the toggle
3. Fixes the UI of the delete custom server popup in dark mode
4. Added a MempoolUrlParser util to parse and normalize mempool server URLs
5. Added a status indicator to the default and custom servers to check if the server is online
6. Tested this setup with .onion links too, if Orbot is running, then those it works without any additional config
7. Made the errors displayed to users easier to understand

Note: This PR has DB changes to add an enableSSL field to mempool table

### CODE REVIEW

File: lib/features/mempool_settings/ui/widgets/set_custom_server_bottom_sheet.dart [hunk 1]
```diff
@@ -127,7 +167,37 @@ class _SetCustomServerBottomSheetState
...
+                      children: [
+                        Icon(
+                          Icons.info_outline,
+                          color: context.appColors.secondary,
+                          size: 20,
+                        ),
+                        const Gap(8),
+                        Expanded(
+                          child: Text(
+                            'Mempool servers are used for fee estimation and opening the block explorer when viewing transaction details.',
```
Comment (i5hi) [inline lib/features/mempool_settings/ui/widgets/set_custom_server_bottom_sheet.dart]: Localization files
