### PR TITLE
fix: exchange statistics and loading indicators improvements

### LINKED ISSUE #1822: Various Issues related to new exchange features
- [ ] When new support chat messages are recieved, we should see a red dot on the messages icon to show that a new unread message exists.
- [ ] There seems to be a significant load time when opening the support chat page - takes upto 5 seconds to load - we should only fetch a small number of messages instead of entire history 
- [ ] We should not use the circular spinner for loading - we should use the LinearProgressIndicator (Seen in both settings and support chat)
- [ ] Trade count should not be in CAD or any fiat unit
Image

### PR DESCRIPTION
**Pull request by mocodesmo**
## Summary

- Replace `CircularProgressIndicator` with `LinearProgressIndicator` on exchange settings screens (statistics, account info, bitcoin wallets)
- Fix trade count display to show plain integer without currency unit
- Add currency conversion for statistics (CAD to user's selected currency using BTC as intermediary)
- Add descriptions for each statistic matching BB-Exchange web app
- Display full numeric values with thousands separators instead of K/M abbreviations
- Show currency code without symbol prefix for clarity (e.g., "279.57 CAD" instead of "$279.57")

## Test plan

- [x] Open Exchange Statistics screen and verify linear progress indicator appears at top during loading
- [x] Verify trade count displays as plain integer (e.g., "5") without currency suffix
- [x] Verify currency values display with thousands separators and currency code (e.g., "1,234.56 CAD")
- [ ] Change currency in Exchange Settings and verify Statistics page reflects the new currency
- [x] Open Account Info screen and verify linear progress indicator
- [x] Open Bitcoin Wallets screen and verify linear progress indicator

Fixes #1822

### CODE REVIEW

File: lib/core/exchange/data/repository/exchange_rate_repository_impl.dart [hunk 1]
```diff
@@ -31,4 +31,24 @@ class ExchangeRateRepositoryImpl implements ExchangeRateRepository {
     final amountBtc = amountFiat / price;
     return BigInt.from((amountBtc * 100000000).truncate());
   }
+
+  @override
+  Future<double> convertFiatToFiat({
```
Comment (i5hi) [inline lib/core/exchange/data/repository/exchange_rate_repository_impl.dart:36]: use correct currency exchange rate from getOrderStats

Comment (i5hi) [reply lib/core/exchange/data/repository/exchange_rate_repository_impl.dart:36]: https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/1838

File: lib/features/settings/ui/screens/exchange/statistics_screen.dart [hunk 2]
```diff
@@ -311,13 +470,141 @@ class _StatCard extends StatelessWidget {
...
+                ],
               ],
             ),
           ),
         ],
       ),
     );
   }
+
+  String _formatWithCurrencyCode(double value, String currencyCode) {
```
Comment (i5hi) [inline lib/features/settings/ui/screens/exchange/statistics_screen.dart]: Alll this formatting code should go into the state...

Comment (i5hi) [reply lib/features/settings/ui/screens/exchange/statistics_screen.dart]: or into a core module

Comment (i5hi) [reply lib/features/settings/ui/screens/exchange/statistics_screen.dart]: thanks @mocodesmo
