### PR TITLE
fix: import mnemonic passphrase and label input keyboard lag

### LINKED ISSUE #1867: Keyboard Lag Issue on Wallet Import Screen
🔗 [View Slack thread](https://slack.com/app_redirect?channel=C09899B4C9Z&message_ts=1770652384.561479)

👤 Asked by: [Basanta Goswami](https://satoshi-portal.slack.com/team/U09E0QJSRH7)

🐞 Users experience significant lag when trying to bring up the keyboard by pressing the input label while importing a new wallet. The keyboard response is so slow that it becomes nearly unusable

### PR DESCRIPTION
**Pull request by basantagoswami**
Fixes: #1867 (Keyboard Lag Issue on Wallet Import Screen)

- addPostFrameCallback guard (hints.first != widget.words[_focusedDisplayIndex])

When you finish typing a word and there's only one possible match, autofill fires: it schedules _onHintTap which sets the word and moves focus to the next field. That's the intended behaviour. But once all 12 words are complete and focus is still on the last word, hints always has exactly one match: the word that's already there. The old code scheduled _onHintTap unconditionally, which called onWordChanged -> parent setState -> rebuild -> scheduled _onHintTap again -> infinite loop. The guard breaks this: if the word is already set to the only matching hint, there's nothing to autofill, so don't schedule the callback.

- Controller text in didUpdateWidget instead of build()

_controller.text = widget.word was being called on every build(). TextEditingController's text setter calls notifyListeners(), which tells Android the text input has changed. With 12 word fields all doing this during a single rebuild, Android tries to reinitialize the IME 12 times - roughly 80ms each - adding up to 1 second of lag. Moving it to didUpdateWidget with a change check means the controller only notifies when the word actually changes for ex via autofill, not on every rebuild.

### CODE REVIEW

File: lib/core/widgets/mnemonic_widget.dart [hunk 1]
```diff
@@ -189,17 +189,30 @@ class MnemonicWord extends StatefulWidget {
 }
 
 class MnemonicWordState extends State<MnemonicWord> {
-  final _controller = TextEditingController();
+  late final _controller = TextEditingController(text: widget.word);
```
Comment (ethicnology) [inline lib/core/widgets/mnemonic_widget.dart]: `late` doesn't seems required if you can instantiate during declaration.

If not strictly needed we should remove it to avoid late initialization errors.

**Review by ethicnology — CHANGES_REQUESTED** [review]
is `late` required ?

File: lib/core/widgets/mnemonic_widget.dart (hunk 1 above)
Comment (basantagoswami) [reply lib/core/widgets/mnemonic_widget.dart]: late isn't strictly needed. did this this instead.

-  late final _controller = TextEditingController(text: widget.word);
+  final _controller = TextEditingController();
+
+  @override
+  void initState() {
+    super.initState();
+    _controller.text = widget.word;
+  }

Comment (ethicnology) [reply lib/core/widgets/mnemonic_widget.dart]: cool!

**Review by ethicnology — APPROVED** [review]

**Review by kumulynja — APPROVED** [review]

**Review by i5hi — APPROVED** [review]

**Review by i5hi — APPROVED** [review]
